parameters:
    pecserke_fixtures.object_transformer.default.class: Pecserke\YamlFixturesBundle\DataTransformer\ObjectTransformer

services:
    pecserke_fixtures.object_transformer.default:
        class: "%pecserke_fixtures.object_transformer.default.class%"

    pecserke_fixtures.object_transformer:
        alias: pecserke_fixtures.object_transformer.default
