language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=2.3
    - SYMFONY_VERSION=v2.4.0-BETA2

before_script:
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source

notifications:
    email:
        - tomas@pecserke.eu
