language: php

php:
    - 5.4
    - 5.3.3

env:
    - SYMFONY_VERSION=2.3

before_script:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev -n

notifications:
    email:
        - tomas@pecserke.eu
