language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
    - SYMFONY_VERSION=2.3

before_script:
    - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION}
    - export PREFER="--prefer-$(if [ `php -v | grep 5.3.3 -c` -eq 0 ]; then echo 'source'; else echo 'dist'; fi)"
    - php composer.phar install --no-interaction $PREFER --dev

notifications:
    email:
        - tomas@pecserke.eu
